name: m_rba
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - et_xmlfile=1.1.0
  - openpyxl=3.0.9
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.7.11
  - setuptools=58.0.4
  - sqlite=3.36.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.0
  - wincertstore=0.2
  - pip:
    - numpy==1.21.4
    - pandas==1.3.4
    - python-dateutil==2.8.2
    - pytz==2021.3
    - scipy==1.7.2
    - six==1.16.0
